apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auto-deploy-api
  namespace: auto-deploy
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auto-deploy-api
                port:
                  number: 80
